name: Render Markdown to PDF

on: 
  workflow_dispatch:
    inputs:
      filename:
        description: "Filename of markdown file in docs/ subdir to be rendered"
        required: true
        type: string

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: mkdir output
        
      - uses: docker://pandoc/latex:3.7-ubuntu
        with:
          args: --output=output/result.pdf "docs/${{ inputs.filename }}"
          
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
