name: Render Markdown to PDF

on: 
  workflow_dispatch:
    inputs:
      filename:
        description: "Filename of markdown file to be rendered"
        required: true
        type: string

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get file basename (no extension)
        id: get_file_basename
        run: |
          echo "filename=$(basename ${{ inputs.filename }} .md) > $GITHUB_OUTPUT"
          mkdir output
        
      - uses: docker://pandoc/latex:3
        with:
          args: --output=output/result.pdf ${{ steps.get_file_basename.outputs.filename }}
          
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
